//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modbus {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Modbus.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Specialized use in conjunction with programming commands. The server (or slave) has accepted the request and is processing it, but a long duration of time will be required to do so. This response is returned to prevent a timeout error from occurring in the client (or master). The client (or master) can next issue a Poll Program Complete message to determine if processing is completed. 的本地化字符串。
        /// </summary>
        internal static string Acknowlege {
            get {
                return ResourceManager.GetString("Acknowlege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Argument endPoint cannot be empty. 的本地化字符串。
        /// </summary>
        internal static string EmptyEndPoint {
            get {
                return ResourceManager.GetString("EmptyEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specialized use in conjunction with gateways, indicates that the gateway was unable to allocate an internal communication path from the input port to the output port for processing the request. Usually means that the gateway is misconfigured or overloaded. 的本地化字符串。
        /// </summary>
        internal static string GatewayPathUnavailable {
            get {
                return ResourceManager.GetString("GatewayPathUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specialized use in conjunction with gateways, indicates that no response was obtained from the target device. Usually means that the device is not present on the network. 的本地化字符串。
        /// </summary>
        internal static string GatewayTargetDeviceFailedToRespond {
            get {
                return ResourceManager.GetString("GatewayTargetDeviceFailedToRespond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hex string must have even number of characters. 的本地化字符串。
        /// </summary>
        internal static string HexCharacterCountNotEven {
            get {
                return ResourceManager.GetString("HexCharacterCountNotEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data address received in the query is not an allowable address for the server (or slave). More specifically, the combination of reference number and transfer length is invalid. For a controller with 100 registers, the PDU addresses the first register as 0, and the last one as 99. If a request is submitted with a starting register address of 96 and a quantity of registers of 4, then this request will successfully operate (address-wise at least) on registers 96, 97, 98, 99. If a request is submitted with  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IllegalDataAddress {
            get {
                return ResourceManager.GetString("IllegalDataAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value contained in the query data field is not an allowable value for server (or slave). This indicates a fault in the structure of the remainder of a complex request, such as that the implied length is incorrect. It specifically does NOT mean that a data item submitted for storage in a register has a value outside the expectation of the application program, since the MODBUS protocol is unaware of the significance of any particular value of any particular register. 的本地化字符串。
        /// </summary>
        internal static string IllegalDataValue {
            get {
                return ResourceManager.GetString("IllegalDataValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The function code received in the query is not an allowable action for the server (or slave). This may be because the function code is only applicable to newer devices, and was not implemented in the unit selected. It could also indicate that the server (or slave) is in the wrong state to process a request of this type, for example because it is unconfigured and is being asked to return register values. 的本地化字符串。
        /// </summary>
        internal static string IllegalFunction {
            get {
                return ResourceManager.GetString("IllegalFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specialized use in conjunction with function codes 20 and 21 and reference type 6, to indicate that the extended file area failed to pass a consistency check. 的本地化字符串。
        /// </summary>
        internal static string MemoryParityError {
            get {
                return ResourceManager.GetString("MemoryParityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array networkBytes must contain an even number of bytes. 的本地化字符串。
        /// </summary>
        internal static string NetworkBytesNotEven {
            get {
                return ResourceManager.GetString("NetworkBytesNotEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Specialized use in conjunction with programming commands. The server (or slave) is engaged in processing a long–duration program command. The client (or master) should retransmit the message later when the server (or slave) is free. 的本地化字符串。
        /// </summary>
        internal static string SlaveDeviceBusy {
            get {
                return ResourceManager.GetString("SlaveDeviceBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An unrecoverable error occurred while the server (or slave) was attempting to perform the requested action. 的本地化字符串。
        /// </summary>
        internal static string SlaveDeviceFailure {
            get {
                return ResourceManager.GetString("SlaveDeviceFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Function Code: {1}{0}Exception Code: {2} - {3} 的本地化字符串。
        /// </summary>
        internal static string SlaveExceptionResponseFormat {
            get {
                return ResourceManager.GetString("SlaveExceptionResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid function code value for SlaveExceptionResponse. 的本地化字符串。
        /// </summary>
        internal static string SlaveExceptionResponseInvalidFunctionCode {
            get {
                return ResourceManager.GetString("SlaveExceptionResponseInvalidFunctionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The compact framework UDP client does not support timeouts. 的本地化字符串。
        /// </summary>
        internal static string TimeoutNotSupported {
            get {
                return ResourceManager.GetString("TimeoutNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UdpClient must be bound to a default remote host. Call the Connect method. 的本地化字符串。
        /// </summary>
        internal static string UdpClientNotConnected {
            get {
                return ResourceManager.GetString("UdpClientNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown slave exception code. 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WaitToRetryMilliseconds must be greater than 0. 的本地化字符串。
        /// </summary>
        internal static string WaitRetryGreaterThanZero {
            get {
                return ResourceManager.GetString("WaitRetryGreaterThanZero", resourceCulture);
            }
        }
    }
}
